apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-provider
spec:
  selector:
    matchLabels:
      app: taxi-provider
  replicas: 1
  template:
    metadata:
      labels:
        app: taxi-provider
    spec:
      containers:
        - name: taxi-provider
          image: taxi-provider-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
---

apiVersion: v1
kind: Service
metadata:
  name: taxi-provider-svc
spec:
  selector:
    app: taxi-provider # APP!!! NOT TYPE!!!
  ports:
    - protocol: TCP
      port: 8090
      name: tcp-90
      targetPort: 8090
  type: NodePort