spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://psql-taxi:5432/taxi
    username: admin
    password: password

app:
  client:
    host: http://taxi-provider-svc:8090/info
  schedule:
    cron: "*/10 * * * * *"
  request:
    number: 1
  coordinate:
    start-longitude: 50.189683
    start-latitude: 53.222579
    finish-longitude: 50.102834
    finish-latitude: 53.199131
  provider:
    url: taxi-provider-svc:8090/taxi/price
    clid: ${TAXI_CLID}
    apiKey: ${TAXI_APIKEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  # Section for prometheus. Also need add 'prometheus' to management.endpoints.web.exposure.include, if not "*"
  # Available at host/actuator/prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true